site_name: checkatlas
theme: readthedocs
repo_url: https://github.com/becavin-lab/checkatlas
site_url: https://checkatlas.readthedocs.io/

nav:
  - Overview:
    - Summary: "index.md"
    - Installation: "installation.md"
    - Usage: "usage.md"
    - Examples: "examples/examples.md"
    - Contributing: "contributing.md"
  - Metrics:
    - Summary: "metrics/metrics.md"
    - Clustering:
      - Silhouette: "metrics/silhouette.md"
    - Classification:
      - 'Rand index': "metrics/rand_index.md"
    - 'Dimensionality reduction':
      - 'Kruskal stress': "metrics/kruskal_stress.md"
  - API:
    - API: "API.md"


plugins:
  - search
  - mkdocstrings:
      enabled: !ENV [ ENABLE_MKDOCSTRINGS, true ]
      custom_templates: templates
      default_handler: python
      handlers:
        python:
          import:
            - https://docs.python-requests.org/en/master/objects.inv
          options:
            show_source: true
            heading_level: 4
