site_name: checkatlas
theme: readthedocs
repo_url: https://github.com/becavin-lab/checkatlas
site_url: https://checkatlas.readthedocs.io/

nav:
  - Overview: "index.md"
  - Installation: "installation.md"
  - Examples: "examples/examples.md"
  - Metrics: "metrics/metrics.md"
  - API: "API.md"
  - Contributing: "contributing.md"

plugins:
  - search
  - mkdocstrings:
      enabled: !ENV [ ENABLE_MKDOCSTRINGS, true ]
      custom_templates: templates
      default_handler: python
      handlers:
        python:
          import:
            - https://docs.python-requests.org/en/master/objects.inv
          options:
            show_source: false
            heading_level: 4
