NOADATA: true
NOMETRIC: false
NOMULTIQC: true
NOQC: true
NOREDUCTION: true
config: config/test_config.yaml
debug: true
metric_annot:
- rand_index
metric_cluster:
- silhouette
metric_dimred:
- kruskal_stress
multiqc: CheckAtlas_MultiQC
nextflow: 2
obs_cluster:
- cell_type
- CellType
- celltype
- ann_finest_level
- cellranger_graphclust
- seurat_clusters
- louvain
- leiden
- orig.ident
path: /Users/christophebecavin/Documents/testatlas
qc_display:
- violin_plot
- total_counts
- n_genes_by_counts
- pct_counts_mt
