NOADATA: false
NOMETRIC: false
NOMULTIQC: true
NOQC: true
NOREDUCTION: true
config: config/metric_config.yaml
debug: true
metric_cluster: []
metric_annot: []
metric_dimred: [kruskal_stress]
multiqc: CheckAtlas_MultiQC
nextflow: 0
obs_cluster:
- cell_type
- CellType
- celltype
- ann_finest_level
- cellranger_graphclust
- seurat_clusters
- louvain
- leiden
- orig.ident
path: /Users/christophebecavin/Documents/testatlas
qc_display:
- violin_plot
- total_counts
- n_genes_by_counts
- pct_counts_mt
resume: false
