NOADATA: true
NOMETRIC: true
NOMULTIQC: true
NOQC: false
NOREDUCTION: true
config: config/test_config.yaml
debug: true
metric_annot: []
metric_cluster: []
metric_dimred:
- kruskal_stress
multiqc: CheckAtlas_MultiQC
obs_cluster:
- cell_type
- CellType
- celltype
- ann_finest_level
- seurat_clusters
- louvain
- leiden
- orig.ident
path: /Users/christophebecavin/Documents/testatlas
qc_display:
- violin_plot
- total_counts
- n_genes_by_counts
- pct_counts_mt
thread: 1
